export const DestinationDetails=[
        { 
        "id": 0,
         "dest": 'KAZBEGI',
         "imgBg":"images/destinations-1-img-14.jpg",
          "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
          "Desc":"KAZBEGI National Park is located on the northern slopes of the mighty Caucasus range, and its protected area covers a total of over 8,700 hectares. At 5,047 metres above sea level, Kazbegi Mountain (or Mkinvartsveri) is the third highest mountain in Georgia, and is surrounded by myths and religious tradition. According to Greek mythology, as punishment for teaching mankind how to make fire, the Titan Prometheus was chained to a mountainside in the Caucasus for all eternity. According to Georgian stories, it was the icy slopes of Kazbegi to which he was chained. Prometheus (known as Amirani in Georgia) was supposedly imprisoned in a cave 4,000 meters high. The cave, now called Betlemi (Bethlehem), later served as a dwelling for orthodox monks, and is said to have contained many sacred relics, including Abraham’s tent and Christ’s manger. Hot springs and acidic and carbonated lakes surround the mountain, and earth tremors are fairly frequent. Covered with 135 square kilometres of glacier, Kazbegi is a great place for ice climbing and mountaineering. The Dariali Gorge is an impossibly steep cleft in the mountains connecting Russia and Georgia, running for 18km from Stepantsminda to the Russian border at Zemo Larsi (Upper Lars). For millennia, this mountain passage has been strategically crucial, and has been fortified since at least 150 BC. In places, the cliff faces are more than 1,000m high, and medieval watchtowers, waterfalls and wildlife make this one of the most incredible roads in the world. The steep valleys either side of the gorge are great places for bird watching. Eagles, hawks and the massive griffon vultures all nest among the rocky outcrops. The town of Stepantsminda (also called Kazbegi) itself is charming and a wonderful base camp for exploring the region further. There are many guesthouses where locals are happy to treat you like family, rustic and beautiful with views of the mountains, and often the picturesque Gergeti Trinity Church."
        },
        { "id": 1, 
        "dest": 'Tbilisi', 
        "imgBg":"images/Tbilisi.jpg",
        "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
        "Desc":"Tbilisi, Georgia's ancient and vibrant capital city spreads out on both banks of the Mtkvari River, and is surrounded on three sides by mountains. The most widely accepted variant of the legend of Tbilisi's founding says that in the mid-5th century AD, King Vakhtang I Gorgasali was hunting in the heavily wooded region with a falcon. The King's falcon allegedly caught or injured a pheasant during the hunt, after which both birds fell into a nearby hot spring and died from burns. King Vakhtang became so impressed with the hot springs that he decided to cut down the forest and build a city. The name Tbilisi derives from the Old Georgian word 'tbili', meaning warm. Archaeological studies of the region indicate human settlement in the area early as the 4th millennium BC." 
        },
        { "id": 2,
         "dest": 'Mtskheta',
         "imgBg":"images/BgDestMtskheta.jpg",
         "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
        "Desc":"Mtskheta is a UNESCO World Heritage Site. It has been inhabited since before 1,000 BC and was once the capital of the early Kingdom of Iberia (today’s Eastern Georgia).  Just 20 km from Tbilisi, at the confluence of the Mtkvari and Aragvi rivers, the city is located on an ancient trade route. Archaeologists have unearthed evidence of Mtskheta’s status as a major trading post. Glass perfume bottles, Greek and Aramaic writings, pottery, metalwork and jewelry have all been unearthed in abundance here, and many examples are on show in the town’s museum.                  The ancient geographer Strabo described Mtskheta as a highly developed city with a water supply system, markets and stone houses. Mtskheta was also the religious centre of the country, with a number of major shrines to Georgia’s pagan pantheon; these would later be replaced by churches when St. Nino converted the country to Christianity in around 337 AD.  Although the capital was moved to the more easily defended Tbilisi at the beginning of the VI century, Mtskheta continued to be the coronation and burial place of Georgian kings, and the seat of the Patriarch, who is also known as the Bishop of Mtskheta. Today, the lovely old town has a laid back, village feel, especially compared to the more hectic pace of Tbilisi."
        },

        { "id": 3,
         "dest": 'Gori',
         "imgBg":"images/BgDestGori.jpg",
         "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
        "Desc":"The original fortress, constructed on a hilltop, was named Gori (meaning hill in English), and was mentioned in the Georgian chronicles as early as the VII century. Some historians believe that the fortress was built by Byzantine Caesar Heraclius to store ammunition battles against the Persians.                                                                         Just after the XI century the area became an active center for trade. According to some historians, this was due to David the Builder founding the town. Because of its geographical location, enemies frequently targeted the fortress, as conquering it enabled control of the whole Shida Kartli region. The fortress has been invaded many times and controlled by Ossetians, Iranians and Persians, amongst others. The stronghold has been repeatedly destroyed and rebuilt. The current iteration of the fortress was built in 1774, during the reign of Erekle II, but was significantly damaged by an earthquake in 1920. The Stalin Museum includes the memorial house where Joseph Stalin (1879-1953) was born, a museum building with a tower, and Stalin’s personal train car he used to visit Tehran, Yalta, and Potsdam. There are many unique exhibits displayed here, including personal belongings and collections of paintings, photos, films and other important historical artifacts."
        },

        { "id": 4,
         "dest": 'Zugdidi',
         "imgBg":"images/images/11dayAz-Georgia.jpg.jpg",
         "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
        "Desc":"The city is the capital of the Samegrelo-Zemo Svaneti region, which combines Samegrelo (Mingrelia) and Svaneti. The name 'Zugdidi' means 'big/great hill' in Laz and Mingrelian.     Zugdidi served as the capital of the principality of Mingrelia (Odishi) until 1867, when the principality was abolished by the Russian Empire. In 1993 the administration of the first President of Georgia, Zviad Gamsakhurdia, was here."
        },

        { "id": 5,
         "dest": 'Kutaisi',
         "imgBg":"images/BgDestKutaisi.jpg",
         "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
        "Desc":"Kutaisi, the capital of Imereti, is Georgia’s second largest city after Tbilisi. Elegant, tree lined streets with 19th century houses stretching down to the banks of the Rioni River, along with several attractive parks, make Kutaisi a very beautiful place to stroll around and take in the many sights.                                                                        In the Jewish Quarter a number of synagogues demonstrate the long history of the Georgian Jewish community. The town’s largest synagogue, built in 1866, can seat 500 worshipers. The magnificent churches of Bagrati and Gelati – both UNESCO world heritages sites – testify to the importance of the region."
        },

        { "id": 6,
         "dest": 'Mestia',
         "imgBg":"images/11dayAz-Georgia.jpg",
         "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
        "Desc":"Mestia, the main regional center of Zemo (Upper) Svaneti, is situated 456 km from Georgia’s capital city, Tbilisi, and is 1,500 meters above sea level. It is the starting point for most trips to Svaneti, with a range of hotels, guesthouses and local travel services, and makes a convenient base for exploring the area. From the center of Mestia it is possible to hike up to the glaciers at the foot of mount Ushba, or take horses into the pristine alpine meadows. New ski resorts Hatsvali and Tetnuldi attract the attention of winter sports lovers who are looking for the new places and challenges.                                                  Tourists interested in religious history will find plenty of examples of wall paintings, frescoes and icons from the Middle Ages in the churches around Mestia. Within Mestia, the Church of Saint George contains well-preserved crosses and icons from the XII century. Additionally, Pusdi Church still contains fragments of XIII century wall paintings."
        },

        { "id": 7,
         "dest": 'Borjomi',
         "imgBg":"images/7daygeorgiajpg",
         "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
        "Desc":"Borjomi is famous for its mineral water industry (which is the number one export of Georgia). Archaeological excavations have revealed the existence of stone baths in the area, proving that these mineral waters have been utilized by people for thousands of years. Because of the supposed restorative and healing powers of the area's mineral springs, it is a frequent destination for people with health problems. Borjomi is also home to the most extensive ecologically-themed amusement park in the Caucasus."
        },

        { "id": 8,
         "dest": 'Sairme',
         "imgBg":"images/7daygeorgia2",
         "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
        "Desc":"The health resort Sairme is located to the south of Kutaisi, 950 meters above sea level. This unique location offers healing springs, an ecologically clean environment, and beautiful nature. It is located in a subtropical mountainous area.                                         The medicinal qualities of the mineral and thermal springs at Sairme were already well known in the 19th century. Several small springs flow on the territory of the resort. They differ in their chemical composition and medicinal treatment qualities, and each spring was given specific number after chemical analyses were conducted. The uniqueness and medicinal treatment capabilities of each of the springs was precisely defined, contemporary-style drinking fountains were installed, making the process of drinking water out of the medicinal springs and determining the correct dosage for guests more comfortable.                                                           Several illnesses are said to be able to be treated by the springs of Sairme:                   Pump room № 1: Urinary calculus disease (treatment of chronic kidney disease, salt diathesis, as well as prophylactic treatment )                                                               Pump room № 2 : Bile-pebble diseases ( chronic cholecystitis, chronic hepatitis, not aggravated form, as well as for prophylactic purposes)                                                     Pump room № 3 : Disturbance of metabolism ( diabetes, salt diathesis, arthritis, osteochondrosis)Pump room № 4 : Gastrointestinal diseases ( peptic ulcer, disease, increased or decreased acidity, colitis)"
        },

        { "id": 9,
        "dest": 'Akhaltsikhe',
        "imgBg":"images/7daygeorgia6.jpg",
        "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
       "Desc":"Akhaltsikhe is a town in Southern Georgia, founded in Middle Ages. Its name means “a new fortress”, because the town’s fortress used to be the most important landmark of the region. In 1579 it was a center of a region of Ottoman Empire, then, during Russian – Turkish war in 1828 – 1829, it was brought back to Georgia, which used to be a part of Russian Empire.               Now, the huge freshly renovated fortress of Rabati remains the main landmark of Akhaltsikhe. Its upper part includes the castle of Jakeli family, where the Museum of Samtskhe-Javakheti region is situated; there are also an Akhmediye Mosque, an orthodox church, an amphitheatre and a citadel. The other part of Rabati includes touristic objects as hotels, cafes, restaurants, an information center, and even a marriage hall. It is a very beautiful place for a wedding ceremony and a romantic photo shooting, indeed!                                                              Beside this, there are also several interesting places near Akhaltsikhe: an ancient fortress of Atskuri, which has been constructed in the X century, and also Saphara monastery, which kept its beauty even after the most difficult years in Georgian history.                                   If we talk about important landmarks of Samtskhe-Javakheti region, we can’t avoid mentioning Vardzia, an impressive cave town founded by King George III in the XII century. During its golden time it accommodated around 50.000 people. The infrastructure included living quarters, wine cellars, religious places like churches or monasteries, and even a library. There was even a sewerage system in the town! Hard to believe, that already in XII century far in the mountains people could live in such a developed town hewn in rocks… That’s why you have to go to Vardzia to see it with your own eyes!" 
       },
       { "id": 10,
        "dest": 'Kvareli',
        "imgBg":"images/7daygeorgia7.jpg",
        "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
       "Desc":"The small, pretty town of Kvareli is located 150 kilometers from Tbilisi, and is both an interesting place for a day trip, and the starting point for a longer tour throughout Kakheti. Wine lovers, nature fans, and history connoisseurs will all find something for themselves here! Wine is the blood of Kakheti and of Georgia, and Kvareli is an important vessel." 
       },

        { "id": 11,
        "dest": 'Sighnaghi',
        "imgBg":"images/11dayAz-Georgia4.jpg",
        "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
       "Desc":"City of wine and love, as it is being called in recent years, is very much appealing to those who are tired of rush and hustle, and like everything lovely, cute and small. Walking through Sighnaghi, you might feel like in Italy - the architecture is pretty similar to small Italian towns. Romantic cobbled streets, carved balconies, 24/7 marriage registration... What is there in this town for those who don’t want to get married right now? " 
       },

      
       { "id": 12,
        "dest": 'Gudauri',
        "imgBg":"images/11dayAz-Georgia7.jpg",
        "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
       "Desc":"GUDAURI is the best ski resort in Georgia with well-developed infrastructure, the greatest difference in altitude, and unlimited possibilities for freeride, back country (ski touring). The resort is the highest settlement on the Georgian Military Road (the old name 'Heavenly Gorge') at the altitude of 2000 m. The season in Gudauri begins in early December and lasts till the end of April. From Tbilisi Gudauri can be reached in approximately 2 hours.                             The highest point of the resort is Mount Sadzele - 3307 m above the sea level. The summit Kudebi (3007) is another popular destination, because one can ski basically from any side of the mount, 360 degrees.                                                                                   Chair lifts (Doppelmayr, Austria) and a gondola line (POMA, France) make available skiing and snowboarding along the southern slopes (70 km certified trails of various difficulty levels) at the altitude from 3275 m to 2000 m, with altitude difference of 1275 meters.                     Ski rental are located in several places: in the village of Lower Gudauri, and in the Upper Gudauri, near the gondola station.                                                          Freeride is possible both along the trails near the ski lifts and in the neighboring area along the western and eastern slopes of the mountains Chrdili, Bidara and the northern slopes of Mt. Sadzele (Kobi Gorge). Adrenaline seekers also have the chance to try paragliding, speedriding (an extreme mix of skiing and paragliding) and heli-skiing." 
       },

        { "id": 13,
         "dest": 'Bakuriani',
         "imgBg":"images/11daysGeorgia5.jpg",
         "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
        "Desc":"Located at 1,700 m in the Borjomi region of Georgia, Bakuriani is nestled in the shadows of the breathtaking Caucasus Mountains, only a three-hour drive from Tbilisi. Home to dozens of alpine slopes and cross-country trails, it offers some of the most spectacular skiing and snowboarding in Europe.                                                                      Originally developed as an Olympic training facility, unsurprisingly, Bakuriani is Georgia’s most popular winter sports and recreation destination. Enjoy the downhill ski runs, cross-country trails, horseback tours, sledding or simply take long walks through beautiful snowy forests. There are several main trails in Bakuriani, one of which is Kokhta (2,255 m high) is a 4 km ski run with difficult and medium difficulty slopes. This is the oldest ski area in Bakuriani.  Didveli (1861 m) has one on the most amazing trails. From here you can catch a gondola to the slopes of Mt. Sakvelo, and ski a range of blue and red routes. The longest piste is around 4 km long. Advanced skiers can continue further up the mountain by catching a chairlift at the top of the gondola to almost the very top of Mt. Sakvelo itself. Here, you can enjoy stretching your ski-legs on very steep and difficult red and black runs.                                       Totally renovated resort Mitarbi (1500m) was able to accept its first visitors after 30 years on December 25, 2016. Winter sport lovers are offered to try 3 new ski lifts, 9 km ski pistes suitable for intermediate, expert and advance skiers/snowboarders, joining ski piste for Kokhta and Mitarbi, modern infrastructure and new unforgettable experiences.                   Bakuriani’s cross-country trails attract experts as well as beginners. Two of the most challenging runs begin on Mt. Kokhta and Mt. Didveli. If skating is your winter pastime, Bakuriani offers plenty of opportunities, among them at Bakuriani Park and the rink at the Hotel Edem. The hills and valleys around Bakuriani are ideal for snowmobiling, but if you prefer to get around the old-fashioned way, horse- drawn sleighs are the traditional mode of winter transportation in Bakuriani, so for a romantic treat, take a romantic sleigh-ride around the picturesque village.                                                                          Guide services, including renting single and double-seat snowmobiles, are available through many hotels and shops." 
        },

        { "id": 14,
         "dest": 'Hatsvali',
         "imgBg":"images/11daysGeorgia2.jpg",
         "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
        "Desc":"Surrounded by mighty 5000 m peaks, Svaneti is one of Georgia’s most historic and unique areas and a real skiers’ dream. Until recently, Svaneti was best known for its superb house-towers, most of them dating back to the 12-13th centuries, which line the valleys and served as look-out posts against the threat of invasion. Those towers belong to UNESCO World Heritage List.                                                                                   In Svaneti, there are two modern white resorts: Hatsvali and Tetnuldi. The first one started operating several years ago. It is located in 8 km from the central village of Svaneti, Mestia. The upper cable car station is located on Mount Zuruldi (2347 m). The difference in altitude is 482 m.                                                                                     Currently, there are three runs: red (1900 m), blue (2600 m) and the trail for beginners (300 m). Basically, skiers of every level can enjoy one of the world’s most picturesque resorts. Freeride and ski tour lovers will also find good slopes and new challenges for themselves. As the resort grows and develops, it is also possible to find tailor-made ski-tours, one or two-day trips to take you to places never skied before." 
        },

        { "id": 15,
         "dest": 'Tetnuldi',
         "imgBg":"images/11daysGeorgia8.jpg",
         "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
        "Desc":"Svaneti, one of the most authentic and beautiful corners of Georgia, is so different from the rest of the country, that it’s not surprising that it’s been a popular summertime holiday destination. Nowadays most tourists are looking to the mountains, not to the valleys… And the mountains are becoming more and more appealing also in wintertime.                                The second biggest national winter resort (after Gudauri), Tetnuldi, is operation since February 2016. It is located at the same-name mountain. Three POMA lifts will deliver you to an altitude from 1600 m to 3165 m. The trails have different difficulty level; the total length is 25 km, and the longest one is 9.5 km. The ski lifts operate from 10:00 to 16:00 yet.                        As the resort is very young, the accommodation and après-ski is still in process of development. But as Tetnuldi is close to Mestia, it is possible to go there with bus or taxi every day and stay in Mestia overnight.                                                                         When you’re not skiing, enjoy your time exploring Mestia, local cuisine and a great museum, a treasure trove of exquisite icons and artifacts gathered from Svaneti’s many remote churches and villages, preserved in this natural mountainous fortress during centuries." 
        },

        { "id": 16,
         "dest": 'Goderdzi',
         "imgBg":"11daysGeorgia1.jpg",
         "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
        "Desc":"In December 2015 a new ski resort Goderdzi has been opened in the mountainous Ajara. First of all it is attractive to those, who want to combine a trip to the sea and skiing in the winter vacation.                                                                                       If you drive or ride a bus from Batumi, the central town of Ajara region, you reach Goderdzi in 2 hours. The resort is not big yet. Two gondola lifts are operating there. The highest point is 2390 m above the sea level, the altitude difference is around 690 m. The whole day ski pass will cost you 25 lari (approximately 12 USD).                                                   Goderdzi is good as for skiing and boarding at the prepared pistes, as well as for freeride. Winters are usually snowy there, so you won’t have problems with finding fresh powder at the slopes.                                                                                           How to get to Goderdzi:                                                                         If you drive from Batumi, the central town of Adjara region, you reach Goderdzi in 2 hours. The 4x4 car is needed, as the road is not paved. The direct public transport is not available in winter, but you can take a bus to Danisparauli village (they run daily at 11:15 and 15:10) for 7 lari and take a cab in Danisparauli for approximately 25 lari/car. Another option is to take a minibus to Khulo from Batumi old bus station (they run every hour from 9 AM to 6 PM) and again, take a free shuttle up there (the schedule can be specified in Khulo information center)."
        },

        { "id": 17,
         "dest": 'Anaklia',
         "imgBg":"images/11daysGeorgia.jpg",
         "img": ["images/tour-2-img-3-gallery.jpg","images/tour-2-img-4-gallery.jpg","images/tour-2-img-5-gallery.jpg","images/tour-2-img-6-gallery.jpg","images/tour-2-img-7-gallery.jpg","images/tour-2-img-8-gallery.jpg","images/tour-2-img-9-gallery.jpg","images/tour-2-img-10-gallery.jpg"],
        "Desc":"Anaklia is a seaside resort in Western Georgia. Its coastline stretches 8 km along the Black Sea, and there are several modern hotels. At the western end of the promenade the longest pedestrian bridge in Europe (540 meters!) connects the resort to the village of Ganmukhuri, located on the opposite side of the Inguri River.                                            Sandy beaches and sunny weather attract several music festivals to the town. As its popularity grows, Anaklia is poised to become the hottest new destination for summer holidays in Georgia.   You can get to Anaklia from Zugdidi, the central city of the Samegrelo-Zemo Svaneti province, via a minibus or private taxi." 
        },

       

    ]

  